export const staticRoutes: AppRoute.RowRoute[] = [
    {
        name: 'home',
        path: '/',
        title: 'Title Home',
        requiresAuth: true,
        icon: 'icon-park-outline:home',
        componentPath: '/home/index.vue',
        id: 1,
        pid: null,
    },
    {
        name: 'error',
        path: '/error',
        title: 'Error',
        requiresAuth: true,
        icon: 'icon-park-outline:error-computer',
        menuType: 'dir',
        componentPath: null,
        id: 31,
        pid: null,
    },
    {
        name: 'demo403',
        path: '/error/403',
        title: '403',
        requiresAuth: true,
        icon: 'carbon:error',
        order: 3,
        componentPath: '/error/403/index.vue',
        id: 32,
        pid: 31,
    },
    {
        name: 'demo404',
        path: '/error/404',
        title: '404',
        requiresAuth: true,
        icon: 'icon-park-outline:error',
        order: 2,
        componentPath: '/error/404/index.vue',
        id: 33,
        pid: 31,
    },
    {
        name: 'demo500',
        path: '/error/500',
        title: '500',
        requiresAuth: true,
        icon: 'carbon:data-error',
        order: 1,
        componentPath: '/error/500/index.vue',
        id: 34,
        pid: 31,
    },
]
